backend:
  name: git-gateway
  branch: master

# when using the default proxy server port
local_backend: true



publish_mode: editorial_workflow
site_url: https://eroyx.tk
display_url: https://eroyx.tk
logo_url: https://eroyx.tk/assets/images/cms.png

media_folder: "assets/images"
collections:
  - label: "Global Site Settings"
    name: "site_config"
    editor:
      preview: true
    delete: true
    files:
      - label: "Metadata"
        name: "metadata"
        file: "_config.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
            hint: "Ex. My Website"
          - label: "E-mail"
            name: "email"
            widget: "string"
            required: true
            hint: "Ex. johndoe@example.com"
          - label: "Description"
            name: "description"
            widget: "text"
            required: true
            hint: "This keywords will be appeared on search engines."
          - label: "Upload a Logo"
            name: "logo"
            widget: "image"
            required: true
            hint: "Upload optimized logo."
          - label: "Upload a Favicon"
            name: "favicon"
            widget: "image"
            required: false
            hint: "Upload a optimzed image."