backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

logo_url: https://aaroham.netlify.app/uploads/images/aaroham_logo_color.png
site_url: https://aaroham.vercel.app

media_folder: "uploads"
collections:
  - label: "Global Site Settings"
    name: "site_config"
    editor:
      preview: false
    delete: true
    files:
      - label: "Metadata"
        name: "metadata"
        file: "_config.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
            hint: "Ex. My Website"
          - label: "E-mail"
            name: "email"
            widget: "string"
            required: true
            hint: "Ex. johndoe@example.com"
          - label: "Description"
            name: "description"
            widget: "text"
            required: true
            hint: "This keywords will be appeared on search engines."
      - label: "Graphic resources"
        name: "graphic_resources"
        file: "_data/resources.yml"
        fields:
          - label: "Logo"
            name: "logo"
            widget: "image"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "Ex. My Website"
          - label: "Top Bar Colour"
            name: "accent_color"
            widget: "color"
            allowInput: true
            required: true
            hint: "*Use your accent colour."
          - label: "Favicon"
            name: "favicon"
            widget: "file"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "Ex. My Website"
          - label: "Header & Footer Background"
            name: "head_foot_background"
            widget: "image"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "*upload atleast 1280*720 images to get better results."
          - label: "Body Background"
            name: "body_background"
            widget: "image"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "*upload atleast 1280*720 images to get better results."
      - label: "Rule Book"
        name: "rule_book"
        file: "_data/rulebook.yml"
        fields:
          - label: "Upload Rule Book"
            name: "url_rulebook"
            widget: "file"
            media_folder: /uploads/files
            media_library:
              config:
                allow_multiple: false
                choose_url: true
      - label: "Results"
        name: "result"
        file: "_data/result.yml"
        fields:
          - label: "Whole Batch Result"
            name: "url_result"
            widget: "file"
            hint: "Upload .csv format of the data. Only .csv is readed. File name should be 'aaroham.csv'."
            media_folder: /_data
            media_library:
              config:
                allow_multiple: false
                choose_url: true
          - label: "Upload .csv file of result"
            name: "url_pointtable"
            widget: "file"
            hint: "Upload .csv format of the data. Only .csv is readed. File name should be 'livepoints.csv'."
            media_folder: /_data
            media_library:
              config:
                allow_multiple: false
                choose_url: true
                