backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

site_url: https://eroyx.tk
display_url: https://eroyx.tk
logo_url: https://aaroham.netlify.app/assets/logo.png

media_folder: "assets/images"
collections:
  - label: "Global Site Settings"
    name: "site_config"
    editor:
      preview: false
    delete: true
    files:
      - label: "Metadata"
        name: "metadata"
        file: "_config.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
            hint: "Ex. My Website"
          - label: "E-mail"
            name: "email"
            widget: "string"
            required: true
            hint: "Ex. johndoe@example.com"
          - label: "Description"
            name: "description"
            widget: "text"
            required: true
            hint: "This keywords will be appeared on search engines."
      - label: "Graphic resources"
        name: "graphic_resources"
        file: "data/_graphic_resources.yml"
        fields:
          - label: "Logo"
            name: "logo"
            widget: "image"
            media_folder: "assets/images"
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "Ex. My Website"